# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DevMode
email: mohashi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Exchange of developer insights - by Marcelo Ohashi
twitter_username: mgohashi
github_username: mgohashi
minimal_mistakes_skin: dark
search: true
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
breadcrumbs: true
twitter:
  username: mgohashi
facebook:
  username: mgohashi
og_image: /assets/images/me.jpeg
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-163964078-1"
    anonymize_ip: false # default

comments:
  provider: "disqus"
  disqus:
    shortname: "mohashi"

repository: "mgohashi/blog-comments"

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-watch

author:
  name   : "Marcelo Ohashi"
  avatar : "/assets/images/me.jpeg"
  bio    : "An enthusiast that enjoys discussing and work with technology."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://mohashi.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mgohashi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mgohashi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mohashi_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohashi"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mgohashi"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mgohashi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mohashi_"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/mohashi"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
